# Data Manipulation and Analysis with numPy

**Definition** - Numpy (Numerical python) is a fundamental package for scientific computing with python. It provides support for arrays, matrices, and large collection of mathemeatical functions to opearte on these data structures. NumPy arrays are more efficient and provide better performance for numerical operations comapred to python's build in lists.

**Use Case in Real Life** - Numpy can be used in various scientific computing scenarios, such as statistical analysis, signal processing and image processing

# Creating a NumPy Array from a List

In [3]:
pip install numpy

In [2]:
import numpy as np

# Creating a 1D array from a list
arr1 = np.array([1,2,3,4,5])

# Creating a 2D array from list of lists
arr2 = np.array( [[1,2,3], [4,5,6]] )

print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


# Creating Arrays with Functions

In [5]:
# Creating an array of zeroes
zeroes = np.zeros((3,4))
print(zeroes)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Creating an array of ones
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [7]:
# Creating an array with a range of values
range_arr = np.arange(10, 20, 2)                     # (start, stop, step)
print(range_arr)

[10 12 14 16 18]


In [8]:
# Creating an array with random values
random_arr = np.random.rand(3,3)
print(random_arr)

[[0.2205677  0.73082504 0.31293095]
 [0.2105914  0.5981217  0.86455357]
 [0.72028576 0.14990526 0.84307753]]


# Basic Array operations - Element-Wise operations

In [9]:
arr = np.array([1,2,3,4,5])

# element wise addition
print(arr + 2)

[3 4 5 6 7]


In [10]:
# Element wise subtraction
print(arr - 2)

[-1  0  1  2  3]


In [11]:
# Element wise multiplication
print(arr * 2)

[ 2  4  6  8 10]


In [12]:
# Element wise division
print(arr / 2)

[0.5 1.  1.5 2.  2.5]


# Basic Array Operation - Mathematical Functions

In [13]:
arr = np.array([1,2,3,4,5])

# Square Root
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [14]:
# Exponential

print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [15]:
# Logarithm
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [16]:
# Sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


# Indexing and Slicing - Slicing

In [17]:
arr = np.array([1,2,3,4,5])

# Slicing array
print(arr[1:4])     # Elements from index 1 to 3
print(arr[:3])      # First three elements
print(arr[2:])      # Elements from index 2


[2 3 4]
[1 2 3]
[3 4 5]


# Indexing and Slicing - Advanced Indexing

In [18]:
arr = np.array([1, 2, 3, 4, 5])

# Boolean indexing
print(arr[arr > 3])

# Fancy indexing
indices = [0,2,4]
print(arr[indices])

[4 5]
[1 3 5]


# Reshaping and Transposing - Reshaping Arrays

In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping the array
reshaped = arr.reshape((3,2))
print(reshaped)


[[1 2]
 [3 4]
 [5 6]]


# Reshaping and Transposing - Transposing Arrays

In [21]:
arr = np.array( [[1,2,3], [4,5,6]] )

# Transposing the array
transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


# Aggregation Functions - Sum and Mean

In [22]:
arr = np.array( [[1,2,3], [4,5,6]] )

# Sum of all elements
print(np.sum(arr))

21


In [23]:
# Sum along columns
print(np.sum(arr, axis=0))

[5 7 9]


In [24]:
# Sum along rows
print(np.sum(arr, axis=1))

[ 6 15]


In [25]:
# sum of all elements
print(np.mean(arr))

3.5


# Aggregation Functions - Min and Max

In [26]:
arr = np.array([[1,2,3], [4,5,6]])

# Minimum value
print(np.min(arr))

1


In [27]:
# Maximum value
print(np.max(arr))

6


In [28]:
# Index of minimum value
print(np.argmin(arr))

0


In [29]:
# Index of maximum value
print(np.argmax(arr))

5
